import { useMemo,useState } from 'react'
import { Card,MetricCard } from '../../design-system/components/Card'
import { Button } from '../../design-system/components/Button'
import { Badge } from '../../design-system/components/Badge'
import { PageHeader } from '../../shared/components/PageHeader'
import { DataTable,type Column } from '../../design-system/components/DataTable'
import { RowActions } from '../../shared/components/RowActions'
import { useAgreements } from '../../domain/agreements.store'
type Catalog={id:string;name:string;detail:string;status:string}
const catalogs=['Redes','Compradores','KAMs','PPMs','Regionais','Canais','Categorias','Clusters','Marcas','Alavancas','Parâmetros de cálculo','Tipos de apuração','Usuários e papéis','Integrações']
export function AdministrationPage(){const{state,dispatch}=useAgreements();const[active,setActive]=useState('Redes');const rows=useMemo<Catalog[]>(()=>{if(active==='Redes')return [...new Set(state.levers.map(l=>l.network))].map((name,index)=>({id:`network-${index}`,name,detail:`${state.levers.filter(l=>l.network===name).length} alavancas vinculadas`,status:'Ativo'}));if(active==='Compradores')return [...new Set(state.levers.map(l=>l.buyer))].map((name,index)=>({id:`buyer-${index}`,name,detail:'Comprador vinculado a rede',status:'Ativo'}));if(active==='KAMs')return [...new Set(state.levers.map(l=>l.kam))].map((name,index)=>({id:`kam-${index}`,name,detail:'Regional Sudeste',status:'Ativo'}));if(active==='Alavancas')return state.levers.map(l=>({id:l.id,name:l.name,detail:`${l.category} · ${l.automation}`,status:l.status}));if(active==='Integrações')return[{id:'di',name:'Motor DI',detail:'Apuração automática',status:'Operacional'},{id:'sap',name:'SAP / GPro',detail:'Pagamento',status:'Operacional'},{id:'signature',name:'Assinatura digital',detail:'Formalização',status:'Operacional'}];return [{id:'base-1',name:active,detail:'Base cadastral governada',status:'Ativo'}]},[active,state.levers]);const columns:Column<Catalog>[]=[{key:'name',label:active.slice(0,-1)||active,render:r=><strong>{r.name}</strong>},{key:'detail',label:'Informação',render:r=>r.detail},{key:'status',label:'Status',render:r=><Badge tone={r.status==='Ativo'||r.status==='Operacional'?'success':'warning'}>{r.status}</Badge>},{key:'actions',label:'Ações',align:'center',compact:true,render:r=><RowActions onView={()=>dispatch({type:'TOAST',message:`Detalhes de ${r.name}`})} actions={[{id:'edit',label:'Editar cadastro',onClick:()=>dispatch({type:'TOAST',message:`Edição de ${r.name} aberta`})},{id:'history',label:'Ver histórico',onClick:()=>dispatch({type:'TOAST',message:`Histórico de ${r.name} aberto`})}]}/>}];return <div className="page"><PageHeader title="Administração" description="Gerencie as bases cadastrais, papéis e integrações que sustentam o processo." actions={<Button onClick={()=>dispatch({type:'TOAST',message:`Novo registro em ${active}`})}>+ Novo cadastro</Button>}/><div className="metrics"><MetricCard label="Redes" value={String(new Set(state.levers.map(l=>l.network)).size)}/><MetricCard label="Compradores" value={String(new Set(state.levers.map(l=>l.buyer)).size)}/><MetricCard label="KAMs" value={String(new Set(state.levers.map(l=>l.kam)).size)}/><MetricCard label="Alavancas" value={String(state.levers.length)}/><MetricCard label="Integrações" value="3"/></div><div className="detail-tabs admin-tabs">{catalogs.map(item=><button className={active===item?'active':''} onClick={()=>setActive(item)} key={item}>{item}</button>)}</div><Card><DataTable rows={rows} columns={columns}/></Card></div>}
