import { Card,MetricCard } from '../../design-system/components/Card'
import { Button } from '../../design-system/components/Button'
import { Badge } from '../../design-system/components/Badge'
import { PageHeader } from '../../shared/components/PageHeader'
import { DataTable,type Column } from '../../design-system/components/DataTable'
import { RowActions } from '../../shared/components/RowActions'
import { useAgreements } from '../../domain/agreements.store'
type Integration={id:string;name:string;use:string;updated:string;tone:'success'|'warning';status:string}
export function AdministrationPage(){const{state,dispatch}=useAgreements();const rows:Integration[]=[{id:'di',name:'Motor DI',use:'Apuração automática',updated:'Hoje, 10:42',tone:'success',status:'Operacional'},{id:'signature',name:'Assinatura digital',use:'Formalização',updated:'Hoje, 11:23',tone:'success',status:'Operacional'},{id:'sap',name:'SAP / GPro',use:'Pagamento',updated:'Hoje, 09:44',tone:'warning',status:'Atenção'}];const columns:Column<Integration>[]=[{key:'name',label:'Integração',render:r=><strong>{r.name}</strong>},{key:'use',label:'Uso',render:r=>r.use},{key:'updated',label:'Última atualização',render:r=>r.updated},{key:'status',label:'Status',render:r=><Badge tone={r.tone}>{r.status}</Badge>},{key:'actions',label:'Ações',align:'center',compact:true,render:r=><RowActions onView={()=>dispatch({type:'TOAST',message:`Detalhes da integração ${r.name}`})} actions={[{id:'log',label:'Ver log',onClick:()=>dispatch({type:'TOAST',message:`Log de ${r.name} aberto`})}]}/>}];return <div className="page"><PageHeader title="Administração" description="Gerencie dados mestres, papéis e integrações que sustentam o processo." actions={<Button onClick={()=>dispatch({type:'TOAST',message:'Novo cadastro aberto'})}>+ Novo cadastro</Button>}/><div className="metrics"><MetricCard label="Redes" value="3"/><MetricCard label="Compradores" value="5"/><MetricCard label="KAMs" value="4"/><MetricCard label="PPMs" value="2"/><MetricCard label="Alavancas" value={String(state.levers.length)}/></div><div className="section-title"><div><h2>Integrações</h2><p>Saúde dos serviços conectados.</p></div></div><Card><DataTable rows={rows} columns={columns}/></Card></div>}
