import type { Agreement,AppState,KamNextAction,ResponsibilityState } from './agreements.types'
export const brl=(value=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(value)
export const totals=(state:AppState)=>({planned:state.levers.reduce((total,lever)=>total+lever.annualBudget,0),budget:state.agreements.reduce((total,agreement)=>total+agreement.budget,0),measured:state.agreements.reduce((total,agreement)=>total+(agreement.diValue??agreement.realValue??0),0),approved:state.agreements.reduce((total,agreement)=>total+(agreement.approvedValue??0),0),paid:state.agreements.reduce((total,agreement)=>total+(agreement.paidValue??0),0)})
export const currentKAM='Juliana Silva'
export const effectiveTarget=(agreement:Agreement)=>agreement.kamAdjustedTarget??agreement.monthlyTarget
export const sortAgreementsByNetwork=(agreements:Agreement[])=>[...agreements].sort((a,b)=>a.network.localeCompare(b.network,'pt-BR')||a.buyer.localeCompare(b.buyer,'pt-BR')||a.lever.localeCompare(b.lever,'pt-BR')||a.id.localeCompare(b.id,'pt-BR'))
export const selectCurrentVigencia=(state:AppState)=>({year:state.selectedYear,month:Number(state.selectedMonth.slice(5,7))})
export function getMonthStatus(month:number,year:number,currentDate=new Date(2026,6,16)){const currentYear=currentDate.getFullYear(),currentMonth=currentDate.getMonth()+1;if(year<currentYear||(year===currentYear&&month<currentMonth))return'past';if(year===currentYear&&month===currentMonth)return'current';return'future'}
export const selectAgreementsByVigencia=(state:AppState)=>{const actual=state.agreements.filter(agreement=>agreement.month===state.selectedMonth);if(actual.length)return actual;return state.levers.map((lever,index):Agreement=>({id:`PREV-${state.selectedMonth.replace('-','')}-${String(index+1).padStart(2,'0')}`,leverId:lever.id,month:state.selectedMonth,network:lever.network,buyer:lever.buyer,kam:lever.kam,ppm:index%2?'Mariana Costa':'Roberto Lima',lever:lever.name,leverObservation:lever.observation,agreementType:lever.agreementType,poStatus:lever.agreementType==='service'?'pending':undefined,invoiceStatus:lever.agreementType==='service'?'pending':undefined,automation:lever.automation,measurementType:lever.measurementType,plannedTarget:lever.annualTarget/12,monthlyTarget:lever.annualTarget/12,budget:Math.round(lever.annualBudget/12),stage:'Apuração',status:'planned',updatedAt:`Planejado para ${state.selectedMonth}`}))}
export function getResponsibilityState(agreement:Agreement):ResponsibilityState{if(['paid','finished'].includes(agreement.status))return'completed';if(['signed','payment_requested','open_balance'].includes(agreement.status))return'waiting_payment';if(agreement.status==='waiting_signature')return'waiting_signature';if(agreement.status==='waiting_approval')return'waiting_ppm';if(['adjustment_requested','rejected'].includes(agreement.status))return'blocked';if(['in_settlement','waiting_di','manual_pending','di_settled'].includes(agreement.status))return'kam_action_required';return'waiting_external'}
export function getNextActionForKAM(agreement:Agreement):KamNextAction{const map:Record<string,KamNextAction>={in_settlement:{label:'Ajustar dados',type:'review',enabled:true},waiting_di:{label:'Atualizar DI',type:'view',enabled:true},manual_pending:{label:'Confirmar apuração',type:'confirm',enabled:true},di_settled:{label:'Confirmar apuração',type:'confirm',enabled:true},adjustment_requested:{label:'Responder ajuste',type:'respond_adjustment',enabled:true},waiting_signature:{label:'Assinar acordo',type:'signature',enabled:true}};return map[agreement.status]??{label:'Acompanhar acordo',type:'view',enabled:false}}
export const selectCurrentMonthAgreementsForKAM=(state:AppState,kam=currentKAM)=>selectAgreementsByVigencia(state).filter(agreement=>agreement.kam===kam)
export const selectAgreementsRequiringKAMAction=(state:AppState)=>selectCurrentMonthAgreementsForKAM(state).filter(agreement=>['kam_action_required','blocked'].includes(getResponsibilityState(agreement)))
export const selectAgreementsWaitingExternal=(state:AppState)=>selectCurrentMonthAgreementsForKAM(state).filter(agreement=>['waiting_external','waiting_ppm','waiting_signature','waiting_payment'].includes(getResponsibilityState(agreement)))
export const selectAgreementsWithDivergence=(state:AppState)=>selectCurrentMonthAgreementsForKAM(state).filter(agreement=>agreement.status==='adjustment_requested'||agreement.status==='rejected')
export const selectAgreementsCompleted=(state:AppState)=>selectCurrentMonthAgreementsForKAM(state).filter(agreement=>getResponsibilityState(agreement)==='completed')
