import type { Agreement,AppState,KamNextAction,ResponsibilityState } from './agreements.types'
export const brl=(v=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v)
export const totals=(s:AppState)=>({planned:s.levers.reduce((n,l)=>n+l.annualBudget,0),budget:s.agreements.reduce((n,a)=>n+a.budget,0),measured:s.agreements.reduce((n,a)=>n+(a.diValue??a.realValue??0),0),approved:s.agreements.reduce((n,a)=>n+(a.approvedValue??0),0),paid:s.agreements.reduce((n,a)=>n+(a.paidValue??0),0)})
export const currentKAM='Juliana Silva'
export const selectCurrentMonthAgreementsForKAM=(s:AppState,kam=currentKAM)=>s.agreements.filter(a=>a.month===s.selectedMonth&&a.kam===kam)
export function getResponsibilityState(a:Agreement):ResponsibilityState{if(['Pago'].includes(a.status))return'completed';if(a.status==='Saldo em aberto')return'waiting_payment';if(['Aguardando assinatura'].includes(a.status))return'waiting_signature';if(a.status==='Assinado'||a.status==='Pagamento solicitado')return'waiting_payment';if(a.status==='Aguardando aprovação')return'waiting_ppm';if(['Com divergência','Ajuste solicitado'].includes(a.status))return'blocked';if(['Apurado DI','Manual pendente','Confirmado KAM','Pré-preenchido','Exceção','Conferido'].includes(a.status))return'kam_action_required';return'waiting_external'}
export function getNextActionForKAM(a:Agreement):KamNextAction{switch(a.status){case'Pré-preenchido':return{label:'Conferir cadastro',type:'review',enabled:true};case'Exceção':return{label:'Revisar exceção',type:'exception',enabled:true};case'Conferido':return{label:'Gerar acordo',type:'generate',enabled:true};case'Manual pendente':return{label:'Inserir valor real',type:'input_value',enabled:true};case'Apurado DI':return{label:'Confirmar OK',type:'confirm',enabled:true};case'Com divergência':return{label:'Revisar divergência',type:'review',enabled:true};case'Confirmado KAM':return{label:'Enviar para aprovação',type:'send_approval',enabled:true};case'Aguardando aprovação':return{label:'Aguardando PPM',type:'view',enabled:false,reason:'O acordo já foi enviado para o PPM'};case'Ajuste solicitado':return{label:'Responder ajuste',type:'respond_adjustment',enabled:true};case'Aprovado':return{label:'Acompanhar assinatura',type:'signature',enabled:true};case'Aguardando assinatura':return{label:'Aguardando assinatura',type:'view',enabled:false,reason:'Aguardando os signatários'};case'Assinado':return{label:'Acompanhar pagamento',type:'payment',enabled:true};case'Pagamento solicitado':return{label:'Aguardando pagamento',type:'view',enabled:false};case'Saldo em aberto':return{label:'Acompanhar saldo',type:'payment',enabled:true};case'Pago':return{label:'Concluído',type:'view',enabled:true};default:return{label:'Aguardar DI',type:'view',enabled:false,reason:'Aguardando atualização da integração'}}}
export const selectAgreementsRequiringKAMAction=(s:AppState)=>selectCurrentMonthAgreementsForKAM(s).filter(a=>getResponsibilityState(a)==='kam_action_required'||getResponsibilityState(a)==='blocked')
export const selectAgreementsWaitingExternal=(s:AppState)=>selectCurrentMonthAgreementsForKAM(s).filter(a=>['waiting_external','waiting_ppm','waiting_signature','waiting_payment'].includes(getResponsibilityState(a)))
export const selectAgreementsWithDivergence=(s:AppState)=>selectCurrentMonthAgreementsForKAM(s).filter(a=>a.status==='Com divergência')
export const selectAgreementsCompleted=(s:AppState)=>selectCurrentMonthAgreementsForKAM(s).filter(a=>getResponsibilityState(a)==='completed')
