import { useMemo,useState } from 'react'
import { Button } from '../../design-system/components/Button'
import { Card,MetricCard } from '../../design-system/components/Card'
import { DataTable,type Column } from '../../design-system/components/DataTable'
import { Select } from '../../design-system/components/Fields'
import { Drawer } from '../../design-system/components/Overlay'
import { PageHeader } from '../../shared/components/PageHeader'
import { ContextFilters } from '../../shared/components/ContextFilters'
import { BulkActionsBar,InlineCurrencyInput,ValueDiff } from '../../shared/components/TableParts'
import { AutomationTypeBadge,StatusBadge } from '../../shared/components/StatusBadge'
import { RowActions } from '../../shared/components/RowActions'
import { useAgreements } from '../../domain/agreements.store'
import { brl,currentKAM,selectCurrentMonthAgreementsForKAM } from '../../domain/agreements.selectors'
import type { Agreement } from '../../domain/agreements.types'

export function MyAgreementsPage(){
 const{state,dispatch}=useAgreements();const[search,setSearch]=useState('');const[network,setNetwork]=useState('Todos');const[automation,setAutomation]=useState('Todos');const[selected,setSelected]=useState<string[]>([]);const[detail,setDetail]=useState<Agreement>();const all=selectCurrentMonthAgreementsForKAM(state)
 const rows=useMemo(()=>all.filter(a=>(network==='Todos'||a.network===network)&&(automation==='Todos'||a.automation===automation)&&(a.network+a.buyer+a.lever+a.id).toLowerCase().includes(search.toLowerCase())),[all,network,automation,search])
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])
 const bulk=(type:'confirm'|'send_approval')=>{if(type==='confirm')dispatch({type:'CONFIRM_KAM',ids:selected});if(type==='send_approval')dispatch({type:'SEND_APPROVAL',ids:selected})}
 const columns:Column<Agreement>[]=[
  {key:'network',label:'Rede',render:a=><strong>{a.network}</strong>},{key:'buyer',label:'Comprador',render:a=>a.buyer},{key:'lever',label:'Alavanca',render:a=>a.lever},{key:'id',label:'Acordo',render:a=>a.id},{key:'automation',label:'Apuração',render:a=><AutomationTypeBadge type={a.automation}/>},{key:'budget',label:'Orçado',render:a=>brl(a.budget)},{key:'measured',label:'Apurado',render:a=>brl(a.diValue)},{key:'real',label:'Real',render:a=>['Manual pendente','Com divergência','Ajuste solicitado'].includes(a.status)?<InlineCurrencyInput value={a.realValue} onSave={value=>dispatch({type:'SET_REAL_VALUE',id:a.id,value})}/>:brl(a.realValue)},{key:'diff',label:'Diferença',render:a=><ValueDiff base={a.budget} value={(a.diValue??0)+(a.realValue??0)}/>},{key:'status',label:'Status',render:a=><StatusBadge status={a.status}/>},{key:'actions',label:'Ações',align:'center',compact:true,render:a=><RowActions onView={()=>setDetail(a)} actions={[{id:'history',label:'Ver histórico',onClick:()=>setDetail(a)},...(a.status==='Exceção'?[{id:'exception',label:'Editar exceção',onClick:()=>setDetail(a)}]:[]),...(a.status==='Com divergência'?[{id:'evidence',label:'Anexar evidência',onClick:()=>dispatch({type:'TOAST',message:'Evidência adicionada'})}]:[]),...(a.status==='Ajuste solicitado'?[{id:'adjustment',label:'Responder ajuste',onClick:()=>setDetail(a)}]:[]),...(a.status==='Aguardando assinatura'?[{id:'signature',label:'Ver assinatura',onClick:()=>setDetail(a)}]:[]),...(a.status==='Pagamento solicitado'||a.status==='Saldo em aberto'||a.status==='Pago'?[{id:'payment',label:'Ver pagamento',onClick:()=>setDetail(a)}]:[])]}/>}
 ]
 return <div className="page"><PageHeader title="Meus acordos do mês" description="Acompanhe todos os acordos do mês e atue conforme o status de cada item." actions={<Button onClick={()=>bulk('send_approval')}>Enviar confirmados</Button>}/><ContextFilters><Select label="Mês" value={state.selectedMonth} onChange={e=>dispatch({type:'SET_MONTH',month:e.target.value})}><option value="2026-03">Março 2026</option></Select><Select label="Rede" value={network} onChange={e=>setNetwork(e.target.value)}><option>Todos</option>{[...new Set(all.map(a=>a.network))].map(x=><option key={x}>{x}</option>)}</Select><Select label="Tipo de apuração" value={automation} onChange={e=>setAutomation(e.target.value)}><option>Todos</option><option>Automática DI</option><option>Manual KAM</option><option>Híbrida</option></Select><label className="field"><label>Buscar</label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rede, alavanca ou acordo"/></label></ContextFilters><div className="metrics"><MetricCard label="Total no mês" value={String(all.length)} detail={`Carteira de ${currentKAM}`}/><MetricCard label="Com pendência" value={String(all.filter(a=>['Manual pendente','Com divergência','Exceção','Ajuste solicitado'].includes(a.status)).length)}/><MetricCard label="Com divergência" value={String(all.filter(a=>a.status==='Com divergência').length)}/><MetricCard label="Aguardando DI" value={String(all.filter(a=>!a.diValue&&a.automation!=='Manual KAM').length)}/><MetricCard label="Concluídos" value={String(all.filter(a=>a.status==='Pago').length)}/></div><Card><BulkActionsBar count={selected.length}><Button size="sm" variant="tertiary" onClick={()=>bulk('confirm')}>Confirmar OK</Button><Button size="sm" onClick={()=>bulk('send_approval')}>Enviar aprovação</Button></BulkActionsBar><DataTable rows={rows} columns={columns} selected={selected} onToggle={toggle} onToggleAll={()=>setSelected(selected.length===rows.length?[]:rows.map(r=>r.id))}/></Card>{detail&&<KamAgreementDrawer agreement={detail} onClose={()=>setDetail(undefined)}/>}</div>
}
function KamAgreementDrawer({agreement,onClose}:{agreement:Agreement;onClose:()=>void}){return <Drawer title={`${agreement.id} · ${agreement.lever}`} onClose={onClose}><div className="audit"><div><small>Rede / comprador</small><strong>{agreement.network} · {agreement.buyer}</strong></div><div><small>Status atual</small><StatusBadge status={agreement.status}/></div><div><small>Valores</small><strong>Orçado {brl(agreement.budget)} · Apurado {brl(agreement.diValue)} · Real {brl(agreement.realValue)}</strong></div>{agreement.exceptionReason&&<div><small>Comentário</small><strong>{agreement.exceptionReason}</strong></div>}<div><small>Histórico</small><strong>{agreement.updatedAt} · atualização mais recente</strong></div></div><div className="modal-actions"><Button variant="tertiary" onClick={onClose}>Fechar</Button></div></Drawer>}
