import { useState,type ReactNode } from 'react'
import { Button } from '../../design-system/components/Button'
export function TableToolbar({search,onSearch,children,actions}:{search:string;onSearch:(v:string)=>void;children?:ReactNode;actions?:ReactNode}){return <div className="toolbar"><input className="search" value={search} onChange={e=>onSearch(e.target.value)} placeholder="Buscar por rede, comprador ou alavanca"/>{children}<span className="spacer"/><div className="toolbar-actions"><button className="toolbar-link" type="button">⌄ Filtros avançados</button><button className="toolbar-icon" type="button" aria-label="Atualizar tabela" title="Atualizar">↻</button>{actions}</div></div>}
export function BulkActionsBar({count,children,onClear,emptyMessage}:{count:number;children?:ReactNode;onClear?:()=>void;emptyMessage?:string}){if(count<2)return null;return <div className="bulk" role="status"><strong>{count} acordos selecionados</strong>{children??<span className="bulk-empty">{emptyMessage??'Os itens selecionados não possuem ação em massa disponível.'}</span>}{onClear&&<><span className="spacer"/><Button size="sm" variant="tertiary" className="bulk-clear" onClick={onClear}>Limpar seleção</Button></>}</div>}
export function InlineCurrencyInput({value,onSave}:{value?:number;onSave:(v:number)=>void}){
 const[editing,setEditing]=useState(false);const[draft,setDraft]=useState(value?.toString()??'');const[saved,setSaved]=useState(false)
 const commit=()=>{const normalized=Number(draft.replace(/\./g,'').replace(',','.'));if(Number.isFinite(normalized)&&normalized>=0){onSave(normalized);setEditing(false);setSaved(true);setTimeout(()=>setSaved(false),1400)}}
 const cancel=()=>{setDraft(value?.toString()??'');setEditing(false)}
 if(!editing)return <button type="button" className={`inline-money-read ${saved?'is-saved':''}`} onClick={()=>setEditing(true)}>{saved?'Salvo':value===undefined?'Inserir valor':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(value)}</button>
 return <input className="inline-money-input" autoFocus value={draft} placeholder="Inserir valor" onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();commit()}if(e.key==='Escape'){e.preventDefault();cancel()}}}/>
}
export function InlineOkToggle({checked,onToggle}:{checked:boolean;onToggle:(checked:boolean)=>void}){return <button type="button" className={`qualitative-ok-toggle ${checked?'is-checked':''}`} aria-pressed={checked} aria-label={checked?'Desmarcar OK':'Marcar OK'} onClick={()=>onToggle(!checked)}>OK</button>}
export function InlineTargetInput({value,onSave,adjusted}:{value:number;onSave:(v:number)=>void;adjusted?:boolean}){const[editing,setEditing]=useState(false);const[draft,setDraft]=useState(String(value));const commit=()=>{const number=Number(draft.replace(',','.'));if(Number.isFinite(number)&&number>=0){onSave(number);setEditing(false)}};if(!editing)return <button type="button" className="inline-money-read" onClick={()=>setEditing(true)}>{Math.round(value)}{adjusted&&<small> · ajustada</small>}</button>;return <input className="inline-money-input" autoFocus value={draft} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')commit();if(e.key==='Escape'){setDraft(String(value));setEditing(false)}}}/>}
export function ConfirmOkButton({confirmed,onClick}:{confirmed?:string;onClick:()=>void}){return confirmed?<span className="badge badge-success">✓ {confirmed}</span>:<Button size="sm" onClick={onClick}>OK</Button>}
export function ValueDiff({base,value}:{base:number;value:number}){const diff=value-base;return <span className={`value-diff ${diff<0?'negative':''}`}>{diff>0?'+ ':''}{new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(diff)}</span>}
